variable "name" {default = "euclid_azurerm_storage_account_blob_container_sas"}
variable "connection_string" {default = "azurerm_storage_account.storage.primary_connection_string"}
variable "container_name" {default = "azurerm_storage_container.container.name"}
variable "https_only" {default = "true"}
variable "ip_address" {default = "168.1.5.65"}
variable "start" {default = "2018-03-21"}
variable "expiry" {default = "2018-03-21"}
variable "permissions_read" {default = "true"}
variable "permissions_add" {default = "true"}
variable "permissions_create" {default = "false"}
variable "permissions_write" {default = "false"}
variable "permissions_delete" {default = "true"}
variable "permissions_list" {default = "true"}
variable "cache_control" {default = "max-age=5"}
variable "content_disposition" {default = "inline"}
variable "content_encoding" {default = "deflate"}
variable "content_language" {default = "en-US"}
variable "content_type" {default = "application/json"}