variable "name " {default = "euclid_azurerm_application_gateway"}
variable "resource_group_name" {default = "azurerm_resource_group.example.name"}
variable "location" {default = "azurerm_resource_group.example.location"}
variable "sku_name" {default = "Standard_Small"}
variable "sku_tier" {default = "Standard"}
variable "sku_capacity" {default = "2"}
variable "gateway_ip_configuration_name" {default = "my-gateway-ip-configuration"}
variable "gateway_ip_configuration_subnet_id" {default = "azurerm_subnet.frontend.id"}
variable "frontend_port_name" {default = "local.frontend_port_name"}
variable "frontend_port_port" {default = "80"}
variable "frontend_ip_configuration_name" {default = "local.frontend_ip_configuration_name"}
variable "frontend_ip_configuration_public_ip_address_id" {default = "azurerm_public_ip.example.id"}
variable "backend_address_pool_name" {default = "local.backend_address_pool_name"}
variable "backend_http_settings_name" {default = "local.http_setting_name"}
variable "backend_http_settings_cookie_based_affinity" {default = "Disabled"}
variable " backend_http_settings_path " {default = "/path1/"}
variable "backend_http_settings_port" {default = "80"}
variable " backend_http_settings_protocol " {default = "Http"}
variable " backend_http_settings_request_timeout " {default = "60"}
variable "http_listener_name " {default = "local.listener_name"}
variable "http_listener_frontend_ip_configuration_name" {default = "local.frontend_ip_configuration_name"}
variable "http_listener_frontend_port_name" {default = " local.frontend_port_name"}
variable "http_listener_protocol  " {default = "Http"}
variable " request_routing_rule_name" {default = " local.request_routing_rule_name"}
variable "request_routing_rule_rule_type" {default = "Basic"}
variable "request_routing_rule_http_listener_name" {default = "local.listener_name"}
variable "request_routing_rule_backend_address_pool_name" {default = "local.backend_address_pool_name"}
variable "request_routing_rule_backend_http_settings_name" {default = "local.http_setting_name"}