variable "name" {default = "euclid_azurerm_data_factory_trigger_custom_event"}
variable "data_factory_id" {default = "azurerm_data_factory.example.id"}
variable "storage_account_id" {default = "azurerm_storage_account.example.id"}
variable "eventgrid_topic_id" {default = azurerm_eventgrid_topic.example.id}
variable "events" {default = ["event1", "event2"]}
variable "subject_begins_with" {default = "abc"}
variable "subject_ends_with" {default = "xyz"}
variable "annotations" {default = ["example1", "example2", "example3"]}
variable "description" {default = "example description"}
variable "pipeline_name" {default = "azurerm_data_factory_pipeline.example.name"}
variable "pipeline_parameters_Env" {default = "Prod"}
variable "foo" {default = "foo1"}
variable "bar" {default = "bar2"}