variable "name" {default = "euclid_azurerm_data_factory_linked_service_azure_databricks"}
variable "data_factory_id" {default = "azurerm_data_factory.example.id"}
variable "description" {default = "ADB Linked Service via MSI"}
variable "adb_domain" {default = "https://${azurerm_databricks_workspace.example.workspace_url}"}
variable "msi_work_space_resource_id" {default = "azurerm_databricks_workspace.example.id"}
variable "new_cluster_config_node_type" {default = "Standard_NC12"}
variable "new_cluster_config_cluster_version" {default = "5.5.x-gpu-scala2.11"}
variable "new_cluster_config_min_number_of_workers" {default = "1"}
variable "new_cluster_config_max_number_of_workers" {default = "5"}
variable "new_cluster_config_driver_node_type" {default = "Standard_NC12"}
variable "new_cluster_config_log_destination" {default = "dbfs:/logs"}
variable "custom_tag1" {default = "sct_value_1"}
variable "custom_tag2" {default = "sct_value_2"}
variable "config1" {default = "value1"}
variable "config2" {default = "value2"}
variable "spark_environment_variables_envVar1" {default = "value1"}
variable "spark_environment_variables_envVar2" {default = "value2"}
variable "init_scripts" {default = ["init.sh", "init2.sh"]}