variable "name" {default = "euclid_azurerm_data_factory_trigger_blob_event"}
variable "data_factory_id" {default = "azurerm_data_factory.example.id"}
variable "storage_account_id" {default = "azurerm_storage_account.example.id"}
variable "events" {default = ["Microsoft.Storage.BlobCreated", "Microsoft.Storage.BlobDeleted"]}
variable "blob_path_ends_with" {default = ".txt"}
variable "ignore_empty_blobs" {default = true}
variable "activated" {default = true}
variable "annotations" {default = ["test1", "test2", "test3"]}
variable "description" {default = "example description"}
variable "pipeline_name" {default = "azurerm_data_factory_pipeline.example.name"}
variable "pipeline_parameters_Env" {default = "Prod"}
variable "foo" {default = "foo1"}
variable "bar" {default = "bar2"}