variable "name " {default = "euclid_azurerm_cdn_frontdoor_firewall_policy"}
variable "resource_group_name" {default = "azurerm_resource_group.example.name"}
variable "sku_name " {default = "azurerm_cdn_frontdoor_profile.example.sku_name"}
variable " enabled" {default = "true"}
variable "mode" {default = "Prevention"}
variable "redirect_url" {default = "https://www.contoso.com"}
variable "custom_block_response_status_code" {default = "403"}
variable "custom_block_response_body" {default = "PGh0bWw+CjxoZWFkZXI+PHRpdGxlPkhlbGxvPC90aXRsZT48L2hlYWRlcj4KPGJvZHk+CkhlbGxvIHdvcmxkCjwvYm9keT4KPC9odG1sPg=="}
variable "custom_rule_name" {default = "Rule1"}
variable "custom_rule_enabled" {default = "true"}
variable "custom_rule_priority " {default = "1"}
variable "custom_rule_rate_limit_duration_in_minutes" {default = "1"}
variable "custom_rule_rate_limit_threshold" {default = "10"}
variable "custom_rule_type" {default = "MatchRule"}
variable "custom_rule_action " {default = "Block"}
variable "match_condition_match_variable" {default = "RemoteAddr"}
variable "match_condition_operator " {default = "IPMatch"}
variable "match_condition_negation_condition" {default = "false"}
variable "match_condition_match_values " {default = "[10.0.1.0/24, 10.0.0.0/24]"}
variable "custom_rule2_name" {default = "Rule2"}
variable " custom_rule2_enabled" {default = " true"}
variable "custom_rule2_priority" {default = "2"}
variable "custom_rule2_rate_limit_duration_in_minutes" {default = "1"}
variable "custom_rule2_rate_limit_threshold" {default = "10"}
variable "custom_rule2_type" {default = "MatchRule"}
variable "custom_rule2_action" {default = "Block"}
variable " match_condition2_match_variable" {default = "RemoteAddr"}
variable " match_condition2_operator" {default = "IPMatch"}
variable " match_condition2_negation_condition" {default = "false"}
variable "match_condition2_match_values" {default = "[192.168.1.0/24]"}
variable " match_condition3_match_variable" {default = "RequestHeader"}
variable "match_condition3_selector" {default = "UserAgent"}
variable "match_condition3_operator" {default = "Contains"}
variable "match_condition3_negation_condition" {default = "false"}
variable "match_condition3_match_values" {default = "[windows]"}
variable " match_condition3_transforms" {default = "[Lowercase, Trim]"}
variable " managed_rule_type" {default = "DefaultRuleSet"}
variable "managed_rule_version" {default = "1.0"}
variable "exclusion_match_variable" {default = "QueryStringArgNames"}
variable "exclusion_operator" {default = "Equals"}
variable "exclusion_selector" {default = "not_suspicious"}
variable "override_rule_group_name" {default = "PHP"}
variable "rule_rule_id" {default = "933100"}
variable "rule_enabled" {default = "false"}
variable " rule_action " {default = "Block"}
variable "override2_rule_group_name" {default = "SQLI"}
variable "exclusion1_match_variable " {default = "QueryStringArgNames"}
variable " exclusion1_operator" {default = "Equals"}
variable "exclusion1_selector" {default = "really_not_suspicious"}
variable "rule1_rule_id" {default = "942200"}
variable "rule1_action" {default = "Block"}
variable " exclusion2_match_variable" {default = "QueryStringArgNames"}
variable "exclusion2_operator" {default = "Equals"}
variable "exclusion2_selector" {default = "innocent"}
variable "managed_rule1_type" {default = "Microsoft_BotManagerRuleSet"}
variable " managed_rule1_version" {default = "1.0"}
variable "managed_rule1_action" {default = "Log"}



