variable "name" {default = "euclid_azurerm_spring_cloud_gateway"}
variable "spring_cloud_service_id" {default = "azurerm_spring_cloud_service.example.id"}
variable "https_only" {default = "false"}
variable "public_network_access_enabled" {default = "true"}
variable "instance_count" {default = "2"}
variable "api_metadata_description" {default = "example description"}
variable "api_metadata_documentation_url" {default = "https://www.example.com/docs"}
variable "api_metadata_server_url" {default = "https://wwww.example.com"}
variable "api_metadata_title" {default = "example title"}
variable "api_metadata_version" {default = "1.0"}
variable "cors_credentials_allowed" {default = "false"}
variable "cors_allowed_headers" {default = "*"}
variable "cors_allowed_methods" {default = "PUT"}
variable "cors_allowed_origins" {default = "example.com"}
variable "cors_exposed_headers" {default = "x-example-header"}
variable "cors_max_age_seconds" {default = "86400"}
variable "quota_cpu" {default = "1"}
variable "quota_memory" {default = "2Gi"}
variable "sso_client_id" {default = "example id"}
variable "sso_client_secret" {default = "example secret"}
variable "sso_issuer_uri" {default = "https://www.test.com/issueToken"}
variable "sso_scope" {default = "read"}