variable "name" {default = "euclid_azurerm_spring_cloud_container_deployment"}
variable "spring_cloud_app_id" {default = "azurerm_spring_cloud_app.example.id"}
variable "instance_count" {default = "2"}
variable "arguments" {default = ["-cp", "/app/resources:/app/classes:/app/libs/*", "hello.Application"]}
variable "commands" {default = "java"}
variable "Bar" {default = "Bar"}
variable "Staging" {default = "Staging"}
variable "server" {default = "docker.io"}
variable "image" {default = "springio/gs-spring-boot-docker"}
variable "language_framework" {default = "springboot"}
