variable "resource_group_name " {default = "azurerm_resource_group.example.name"}
variable "loadbalancer_id " {default = "azurerm_lb.example.id"}
variable "name" {default = "euclid_azurerm_lb_nat_rule"}
variable "protocol" {default = "Tcp"}
variable " frontend_port_start " {default = "3000"}
variable "frontend_port_end" {default = " 3389"}
variable "backend_port" {default = "3389"}
variable "backend_address_pool_id" {default = "azurerm_lb_backend_address_pool.example.id"}
variable "frontend_ip_configuration_name" {default = "PublicIPAddress"}
