variable "name" {default = "euclid_azurerm_machine_learning_compute_cluster"}
variable "location " {default = "azurerm_resource_group.example.location"}
variable "vm_priority" {default = "LowPriority"}
variable "vm_size" {default = "Standard_DS2_v2"}
variable "machine_learning_workspace_id" {default = "azurerm_machine_learning_workspace.example.id"}
variable "subnet_resource_id" {default = "azurerm_subnet.example.id"}
variable "min_node_count" {default = "0"}
variable "max_node_count" {default = "1"}
variable "scale_down_nodes_after_idle_duration" {default = "PT30S" /*30 seconds */}
variable "type" {default = "SystemAssigned"}
