variable "resource_group_name" {default = "azurerm_resource_group.example.name"}
variable "device_name" {default = "azurerm_databox_edge_device.example.name"}
variable "contact_name" {default = "TerraForm Test"}
variable "contact_emails" {default = "creator4983@FlynnsArcade.com"}
variable "contact_company_name" {default = "Flynn's Arcade"}
variable "contact_phone_number" {default = "(800) 555-1234"}
variable "shipment_address_address" {default = "One Microsoft Way"}
variable "shipment_address_city" {default = "Redmond"}
variable "shipment_address_postal_code" {default = "98052"}
variable "shipment_address_state" {default = "WA"}
variable "shipment_address_country" {default = "United States"}