variable "name" {default ="euclid_azurerm_consumption_budget_management_group"}
variable "management_group_id" {default = "azurerm_management_group.example.id"}
variable "amount" {default = "1000"}
variable "time_grain" {default = "Monthly"}
variable "time_period_start_date" {default = "2022-06-01T00:00:00Z"}
variable "time_period_end_date" {default = "2022-07-01T00:00:00Z"}
variable "dimension_name" {default = "ResourceGroupName"}
variable "dimension_values" {default = "azurerm_resource_group.example.name"}
variable "tag_name" {default = "foo"}
variable "tag_values" {default = ["bar","baz"]}
variable "notification_enabled_true" {default = true}
variable "notification_enabled_true_threshold" {default = "90.0"}
variable "notification_enabled_true_operator" {default = "EqualTo"}
variable "notification_enabled_true_contact_emails" {default = ["foo@example.com", "bar@example.com"]}
variable "notification_enabled_false" {default = false}
variable "notification_enabled_false_threshold" {default = "100.0"}
variable "notification_enabled_false_operator" {default = "GreaterThan"}
variable "notification_enabled_false_threshold_type" {default = "Forecasted"}
variable "notification_enabled_false_contact_emails" {default = ["foo@example.com","bar@example.com"]}